### ISSUE TITLE
Current gold frame idea

### ISSUE THREAD

**Issue by MaximusPM** [Wipie/PepeGoldTracker#7]
Bukentaurus here. I made this mock-up of the idea I was talking about @ CurseForge. Just a simple frame that always displays the current gold you have, without having to actually click anywhere. Should be drag-able anywhere the player wants, but lockable so you don't keep accidentally dragging it around while playing.

![WoWScrnShot_072524_142900](https://github.com/user-attachments/assets/b66daa87-08bf-4955-8309-a8437e4f2e06)

**Comment by Wipie** [comment]
Thanks for contributing with your idea, this will be implemented in v1.5.0, update is currently rolling and should be available July 25th 2024.

I've added options to make it lockable & that you can modify its size.

You can also change displays between Character, Realm (Doesn't support connected realm might add it later on), Account
